### ISSUE TITLE
insert problemo here

### ISSUE THREAD

**Issue by Hardwaregore** [TechDudie/TechDudie#1]
@TechDudie 
u know you can do `git clone https://github.com/TechDudie/Techdudie`, delete all the files, and then do `git add .` then `git commit -m "lol ur code is gone"` and the do a `git push --force`. HAVE FUN!!!!!!!

**Comment by TechDudie** [comment]
beep. 

@Hardwaregore 

[<Entire issue will be deleted in 1 day.>]

**Comment by TechDudie** [comment]
> @TechDudie
> u know you can do `git clone https://github.com/TechDudie/Techdudie`, delete all the files, and then do `git add .` then `git commit -m "lol ur code is gone"` and the do a `git push --force`. HAVE FUN!!!!!!!

invalid url HAHAHAHAHAHAHAHAHAHAHAHHAHAHHAHAHAHA
