### ISSUE TITLE
How to start grassbandits?

### ISSUE THREAD

**Issue by Hardwaregore** [TechDudie/TechDudie#2]
@TechDudie, *please tell me* what commands do u run to start flask? `flask run` gives an error.

**Comment by Hardwaregore** [comment]
@TechDudie, YOU DIDN'T ANSWER MY QUESTION AND CAUSED ME 2 HOURS OF DEBUGGING BECAUSE FLASK AND HEROKU GIVES AN ERROR!!!!!!

**Comment by TechDudie** [comment]
Oh my god

**Comment by TechDudie** [comment]
Ohhhhhh mmyyyyyyy goddddddddddddd

**Comment by TechDudie** [comment]
ummmm lemme thinkkk hmmmmm MAYBE YOU FORGOT TO SET THE APPLICATION PATH WITH EXPORT VARIABLE

**Comment by TechDudie** [comment]
OR USE THE APP PARAM

**Comment by TechDudie** [comment]
$ flask --app idot run
\* Serving Flask app 'idot'
\* Running on http://127.0.0.1:5000 (Press CTRL+C to quit)

**Comment by TechDudie** [comment]
microsoft edge says

“The flask command is installed by Flask, not your application; it must be told where to find your application in order to use it. The FLASK_APP environment variable is used to specify how to load the application.”

**Comment by TechDudie** [comment]
And btw im makeing the program to destroy the blocker
Its called blockbreaker

written in java, python2, and bash (unfortunately) so i can run on school mac no deps required

**Comment by TechDudie** [comment]
Cli/javax.swing&java.awt gui probably not javafx

**Comment by TechDudie** [comment]
(Blockbrekaer suite, includes a forceinstaller for pretty much any app (tested) and a proxy and MePipe and some browser thats a tor knockoff proxying to a herokuapp “vpn”)

**Comment by TechDudie** [comment]
@Hardwaregore

**Comment by Hardwaregore** [comment]
@TechDudie , THEN, WHY IS THERE AN INTERNAL SERVER ERROR THEN?????

**Comment by Hardwaregore** [comment]
ALSO, I DON'T USE FLASK, TO START INSANECHESS, RUN `php -S 127.0.0.1:80`! IT'S THAT EASY, NONE OF THAT `flask --app idot -h 127.0.0.1 -p 80 run` $#1+!!!!!

**Comment by Hardwaregore** [comment]
Also, I deployed ur dum app on heroku and it said application error because some dum path variable is missing. none of that garbage with php

**Comment by Hardwaregore** [comment]
```
┌──(wenqianwang@Wenqians-MacBook-Pro)-[~/Desktop/GrassBandits]
└─$ flask --app GrassBandits run
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: no such option: --app
                                                                                
┌──(wenqianwang@Wenqians-MacBook-Pro)-[~/Desktop/GrassBandits]
└─$ flask -a GrassBandits run   
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: no such option: -a
                                                                                
┌──(wenqianwang@Wenqians-MacBook-Pro)-[~/Desktop/GrassBandits]
└─$ flask run                
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[REQUEST] IP Address: 127.0.0.1
[2022-08-02 19:11:07,052] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wenqianwang/Desktop/GrassBandits/app.py", line 32, in root
    return load("/home/TechDude/grassbandits/static/index.html")
  File "/Users/wenqianwang/Desktop/GrassBandits/app.py", line 12, in <lambda>
    load = lambda file: open(file).read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/TechDude/grassbandits/static/index.html'
127.0.0.1 - - [02/Aug/2022 19:11:07] "GET / HTTP/1.1" 500 -
[REQUEST] IP Address: 127.0.0.1
[2022-08-02 19:11:07,268] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/wenqianwang/Desktop/GrassBandits/app.py", line 25, in static_
    return send_from_directory('/home/TechDude/grassbandits/static', path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/helpers.py", line 767, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wenqianwang/Desktop/GrassBandits/app.py", line 27, in static_
    return load('/home/TechDude/grassbandits/static/404.html')
  File "/Users/wenqianwang/Desktop/GrassBandits/app.py", line 12, in <lambda>
    load = lambda file: open(file).read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/TechDude/grassbandits/static/404.html'
127.0.0.1 - - [02/Aug/2022 19:11:07] "GET /favicon.ico HTTP/1.1" 500 -

```

**Comment by Hardwaregore** [comment]
<img width="1423" alt="Screen Shot 2022-08-02 at 7 11 20 PM" src="https://user-images.githubusercontent.com/88296644/182497594-17c0078d-6209-4ca7-b631-9223661494af.png">

**Comment by Hardwaregore** [comment]
btw, i had to run flask on my MacBook because i shut down my Dell r710 and i didn't want to boot it back up

**Comment by Hardwaregore** [comment]
I tried `heroku create -a grassbandits` and `heroku git push heroku:main` and `flask run -h 192.168.50.189 -p 80`

**Comment by Hardwaregore** [comment]
nvm, i got the webserver to work, i just need to edit YOUR STUPID PYTHON APP FILE

**Comment by TechDudie** [comment]
…
I wrote grassbandits why are you hosting it
Still on pythonanywhere

**Comment by TechDudie** [comment]
> I tried `heroku create -a grassbandits` and `heroku git push heroku:main` and `flask run -h 192.168.50.189 -p 80`

And wrong

**Comment by Hardwaregore** [comment]
@TechDudie, @SirAlexBigBrain asked me to do it.

**Comment by TechDudie** [comment]
Welp scweenshwot

**Comment by TechDudie** [comment]
Keep in mind that although my code is open source redistributment is prohibited
If you host the web server ill report u

**Comment by TechDudie** [comment]
> @TechDudie, @SirAlexBigBrain asked me to do it.

how do i know

**Comment by TechDudie** [comment]
Tell him that i wrote it in the first place

**Comment by Hardwaregore** [comment]
how do i "screenshot" an in person conversation

**Comment by TechDudie** [comment]
And lastly the reason is obvious

**Comment by TechDudie** [comment]
Wait you dont know how to mac screenshot? LOLLOLLLOLL

**Comment by Hardwaregore** [comment]
you wrote GrassBandits FOR him. keyword for

**Comment by TechDudie** [comment]
shift command 3

**Comment by Hardwaregore** [comment]
i know that

**Comment by Hardwaregore** [comment]
he told me IN PERSON

**Comment by TechDudie** [comment]
Then get him on the line

**Comment by Hardwaregore** [comment]
also, the only way for my custom domain to have a SSL cert, only i can host it

**Comment by Hardwaregore** [comment]
i need that loadmaster for SSL. thats why im trying to "priate" a license for it

**Comment by Hardwaregore** [comment]
also, he is on vacation

**Comment by TechDudie** [comment]
Then ill give you legal code permissions, and you give me server access deal?
And if i destroy the server get alex to boot me outta here

**Comment by Hardwaregore** [comment]
deal

**Comment by Hardwaregore** [comment]
i will give you the ssh address

**Comment by TechDudie** [comment]
Just emal it to techdudie@mail.com

**Comment by Hardwaregore** [comment]
`ssh siralexbigbrain@gbserver-ssh.hwgpriv.cf`

**Comment by TechDudie** [comment]
And the password
And ill collab you

**Comment by Hardwaregore** [comment]
it will be live tomorrow

**Comment by TechDudie** [comment]
Then ill fixx it

**Comment by Hardwaregore** [comment]
the password is `siralexbigbrain`

**Comment by TechDudie** [comment]
Whats the domain? Grassbandits.tk?

**Comment by Hardwaregore** [comment]
im not allowed to turn on the loadmaster cause my mom thinks it's too loud.

**Comment by Hardwaregore** [comment]
ill turn it on rn

**Comment by TechDudie** [comment]
Lol

**Comment by Hardwaregore** [comment]
it's live, ssh doesn't work yes. I have to configure it. just go to `thegrassbandits.tk`

**Comment by Hardwaregore** [comment]
bruh, the loadmaster still has to boot. give it 69 seconds

**Comment by TechDudie** [comment]
Btw why dont u have minecraft me and peter and the rest of our friends have been hanging out

**Comment by Hardwaregore** [comment]
im not allowed to have video game

**Comment by TechDudie** [comment]
Why not i can

**Comment by Hardwaregore** [comment]
?

**Comment by TechDudie** [comment]
And minecraft is educational *cough cough*
I play it a bunch

**Comment by TechDudie** [comment]
Im going to the library to 3d print some minecraft stuff

**Comment by TechDudie** [comment]
One of them is a pig head, RIP Technoblade

**Comment by Hardwaregore** [comment]
ok, just give me 1 min, i have to go debug the loadmaster...

**Comment by TechDudie** [comment]
I figured out how to take apart a .dmg or .pkg file i can install any app i want without admin

**Comment by Hardwaregore** [comment]
screw it, just visit the site at 9:15. It should be up

**Comment by Hardwaregore** [comment]
r u gonna be here at 9:15?

**Comment by TechDudie** [comment]
Why not host with heroku

**Comment by Hardwaregore** [comment]
it saids app error because the index path isn't right

**Comment by TechDudie** [comment]
A. Free b. Google can still find it c. Easier d. No im not gonna be here in 1 hour

**Comment by TechDudie** [comment]
Did you start the server?
I can fix it

**Comment by Hardwaregore** [comment]
no, the loadmaster has issues

**Comment by TechDudie** [comment]
wuzz a loedmeistro

**Comment by TechDudie** [comment]
Can this run a server?
![Uploading 51E3BD28-A4BB-447C-B3CB-40B692220A02.png…]()

**Comment by Hardwaregore** [comment]
its set up like this:

WAN
|
My firewall
|
LoadMaster
|.....................|..........................................|
server 1.........server2..............................server3

**Comment by Hardwaregore** [comment]
visit the site anytime tomorrow from 8:00 to 4:00

**Comment by TechDudie** [comment]
Be on from 1pm to 3pm i will be online 3dprinting and gaming

**Comment by TechDudie** [comment]
Bye

**Comment by Hardwaregore** [comment]
bye
